# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='待办事项')),
            ],
            options={
                'verbose_name_plural': '待办事项',
                'verbose_name': '待办事项',
            },
        ),
    ]
